trigger:
- main

stages:
- stage: Build
  jobs:
  - job: J1
    pool:
      vmImage: ubuntu-22.04
    steps:

    - script: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use --name arm32builder
        docker buildx inspect --bootstrap

        docker login -u $(CONTAINER_REGISTRY_USERNAME) -p $(CONTAINER_REGISTRY_PASSWORD) $(CONTAINER_REGISTRY_ADDRESS)
      displayName: 'Setup buildx & Login in CR'

    - script: |
        cd ./modules/$(MODULE_SOIL)
        docker buildx build \
          --builder arm32builder \
          --platform linux/arm/v7 \
          -f Dockerfile.arm32v7 \
          -t $(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_SOIL):$(MODULE_VERSION_SOIL) \
          --cache-from=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_SOIL):cache \
          --cache-to=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_SOIL):cache,mode=max \
          --push .
      displayName: 'Build & Push soil img arm32'

    - script: |
        cd ./modules/$(MODULE_AMBIENT)
        docker buildx build \
          --builder arm32builder \
          --platform linux/arm/v7 \
          -f Dockerfile.arm32v7 \
          -t $(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_AMBIENT):$(MODULE_VERSION_AMBIENT) \
          --cache-from=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_AMBIENT):cache \
          --cache-to=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_AMBIENT):cache,mode=max \
          --push .
      displayName: 'Build & Push ambient img arm32'

    - script: |
        cd ./modules/$(MODULE_LEAVES)
        docker buildx build \
          --builder arm32builder \
          --platform linux/arm/v7 \
          -f Dockerfile.arm32v7 \
          -t $(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_LEAVES):$(MODULE_VERSION_LEAVES) \
          --cache-from=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_LEAVES):cache \
          --cache-to=type=registry,ref=$(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_LEAVES):cache,mode=max \
          --push .
      displayName: 'Build & Push leaves img arm32'

